### ISSUE TITLE
The current model segfaults when predicting new pcap

### ISSUE THREAD

**Issue by siamx** [conmarap/website-fingerprinting#4]
## Issue
When trying to predict a new pcap, the predict script segfaults.
The segfault occurs at line 49 in predict script, method `joblib.load` imported from `sklearn.externals`

```python
from sklearn.externals import joblib
classifier = joblib.load("./classifier-nb.dmp")
```
A quick solution to this was to change replace this method with `load` from `joblib` 

```python
from joblib import load
classifier = load("./classifier-nb.dmp")
```

But this solution fails to load the current trained model -as the dumping format is not compatible- rendering this model useless.

## Environemnt
I faced this issue with two different setups

* 1st setup using debian based os
1. Ubuntu 18.04.1
2. python2.7, python3.5

* 2nd setup was on archlinux
1. Archlinux - Linux  4.19.13
2. python2.7.15 & python3.7.1

## Steps to reproduce
1. Capture a packet using the provided `./pcap/capture.sh duckduckgo`
2. Try to predict this packet using `python predict.py ./pcaps/duckduckgo/duckduckgoXXXXX.pcap`

**Comment by conmarap** [comment]
Thank you for posting this. I'll check it out. It sounds like some version mismatch.

**Comment by conmarap** [comment]
Sorry for not having taken action yet. I have to train a new model from scratch, which takes some time. I'll take care of it once I have some time. For now you can collect packet streams with the provided script and train one of your own.

**Comment by conmarap** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/939247/55741718-ee3ab900-59fb-11e9-8233-9cbb0302cf40.png)
